AWSTemplateFormatVersion: "2010-09-09"
Description: Datasets segundo

Parameters:
  pPipelineReference:
    Type: String
    Default: none

Resources:
  rSegundo:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "{{resolve:ssm:/sdlf/dataset/main}}"
      Parameters:
        pPipelineReference: !Ref pPipelineReference
        pS3Prefix: segundo
        pDeploymentInstance: dev
        pStorageDeploymentInstance: dev