AWSTemplateFormatVersion: "2010-09-09"
Description: SDLF Foundations in elabsdl domain, dev environment

Parameters:
  pPipelineReference:
    Type: String
    Default: none

Resources:
  rAnycompany:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "{{resolve:ssm:/sdlf/foundations/main}}"
      Parameters:
        pPipelineReference: !Ref pPipelineReference
        pChildAccountId: !Ref AWS::AccountId
        pOrg: anycompany
        pDomain: elabsdl
        pDeploymentInstance: dev
        pCicdRole: Admin
