AWSTemplateFormatVersion: "2010-09-09"
Description: Engineering SDLF Team in datalake domain, dev environment

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
  rEngineering:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "{{resolve:ssm:/sdlf/team/main}}"
      Parameters:
        pPipelineReference: !Ref pPipelineReference
        pTeamName: engineering
        pStorageDeploymentInstance: dev